[program:eclipse-dnd-forge-bff]
directory=@@DEPLOY_PATH@@
command=@@DEPLOY_PATH@@/deploy/scripts/run-bff.sh
environment=ECLIPSE_DND_BFF_PATH="@@DEPLOY_PATH@@",DND_BFF_ENV_FILE="@@ENV_FILE@@"
user=eclipse-dnd-bff
autostart=true
autorestart=true
startsecs=3
startretries=5
stopasgroup=true
killasgroup=true
stopsignal=TERM
stdout_logfile=/var/log/supervisor/eclipse-dnd-forge-bff.log
stderr_logfile=/var/log/supervisor/eclipse-dnd-forge-bff.err.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile_backups=3
